language: python
python: 3.5
env:
  - TOX_ENV=py35 BOTO_CONFIG=/tmp/nowhere
  - TOX_ENV=flake8
script:
    - tox -e $TOX_ENV
before_install:
    - cp loadsbroker/tests/.boto ~/.boto
install:
    - pip install tox
notifications:
    email: 
    - tarek@mozilla.com
    - bbangert@mozilla.com
    irc: "irc.freenode.org#mozilla-circus"
    on_success: change
after_success:
  - .coveralls.sh
