[hekad]
maxprocs = 4
base_dir = "/heka/data"
share_dir = "/usr/share/heka"

[MemStats]
type = "FilePollingInput"
ticker_interval = 1
file_path = "/proc/meminfo"
decoder = "MemStatsDecoder"

[ProcStats]
type = "FilePollingInput"
ticker_interval = 1
file_path = "/proc/stat"
decoder = "ProcStatDecoder"

[MemStatsDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_memstats.lua"

[MemStatFilter]
type = "SandboxFilter"
filename = "lua_filters/memstats.lua"
message_matcher = "Type == 'stats.memstats'"

[MemStatsd]
type = "StatFilter"
message_matcher = "Type == 'heka.sandbox.memstat'"

[MemStatsd.Metric.free]
type = "Counter"
name = "memory.free.$hostname"
value = "%MemFreeBC%"

[MemStatsd.Metric.used]
type = "Counter"
name = "memory.used.$hostname"
value = "%MemUsedBC%"

[MemStatsd.Metric.swap]
type = "Counter"
name = "memory.swap.$hostname"
value = "%SwapUsed%"

[ProcStatDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/linux_procstat.lua"

[ProcStatFilter]
type = "SandboxFilter"
filename = "lua_filters/procstat.lua"
preserve_data = true
message_matcher = "Type == 'stats.proc'"

[ProcStatsd]
type = "StatFilter"
message_matcher = "Type == 'heka.sandbox.procstat'"

[ProcStatsd.Metric.cpu_usage]
type = "Timer"
name = "cpu.usage.$hostname"
value = "%cpu_usage%"

[ProcStatsd.Metric.cpu_idle]
type = "Timer"
name = "cpu.idle.$hostname"
value = "%cpu_idle%"

[ProcStatsd.Metric.ctxt]
type = "Counter"
name = "ctxt.$hostname"
value = "%ctxt%"

[StatsdInput]
address = ":8125"

[StatAccumInput]
emit_in_payload = false
emit_in_fields = true
ticker_interval = 1

[DashboardOutput]
ticker_interval = 15

[ProtobufEncoder]

# [TcpOutput]
# address = "$remote_addr"
# use_tls = $remote_secure
# message_matcher = "Type != 'heka.all-report' && Type != 'heka.memstat' && Type != 'heka.statmetric'"
# keep_alive = true
# ticker_interval = 300
# encoder = "ProtobufEncoder"

[InfluxdbLineEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/schema_influx_line.lua"

    [InfluxdbLineEncoder.config]
    skip_fields = "**all_base** FilePath NumProcesses Environment TickerInterval"
    tag_fields = "Hostname Environment"
    timestamp_precision = "s"

[InfluxdbOutput]
type = "HttpOutput"
message_matcher = "Type == 'heka.statmetric'"
encoder = "InfluxdbLineEncoder"
address = "http://$influx_addr/write?db=$influx_db&precision=s"
username = ""
password = ""
