[hekad]
maxprocs = 4
base_dir = "/heka/data"
share_dir = "/usr/share/heka"

[StatsdInput]
address = ":8125"

[StatAccumInput]
emit_in_payload = false
emit_in_fields = true
ticker_interval = 1

[LogstreamerInput]
log_directory = "/var/log"
file_match = '*\.log'
decoder = "ProtobufDecoder"
parser_type = "message.proto"

[DashboardOutput]
ticker_interval = 15

[TcpOutput]
address = "$remote_addr"
use_tls = $remote_secure
message_matcher = "Type != 'heka.all-report' && Type != 'heka.memstat' && Type != 'heka.statmetric'"
keep_alive = true
ticker_interval = 300

[InfluxEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"

[HttpOutput]
message_matcher = "Type == 'heka.statmetric'"
encoder = "InfluxEncoder"
address = "http://$influx_addr/db/$influx_db/series"
method = "POST"
username = "root"
password = "root"
