[hekad]
maxprocs = 4
base_dir = "/heka/data"
share_dir = "/usr/share/heka"

[StatsdInput]
address = ":8125"

[StatAccumInput]
emit_in_payload = false
emit_in_fields = true
ticker_interval = 1

[ProtobufDecoder]

[ScribbleDecoder]

[ScribbleDecoder.message_fields]
Hostname = "$hostname"
run_id|uuid = "$run_id"
collection_id|uuid = "$collection_id"

[LogDecoder]
type = "MultiDecoder"
subs = ["ProtobufDecoder", "ScribbleDecoder"]
cascade_strategy = "all"
log_sub_errors = true

[LogstreamerInput]
log_directory = "/var/log"
file_match = '(?P<Source>[^/]+)\.log(?:\.(?P<Seq>\d+))?$$'
priority = ["Seq"]
differentiator = ["Source", "-$instance_id"]
parser_type = "message.proto"
decoder = "LogDecoder"

[DashboardOutput]
ticker_interval = 15

[TcpOutput]
address = "$heka_addr"
use_tls = $heka_secure
message_matcher = "Type != 'heka.all-report' && Type != 'heka.memstat' && Type != 'heka.statmetric'"
keep_alive = true
ticker_interval = 300

[InfluxEncoder]
type = "SandboxEncoder"
filename = "lua_encoders/statmetric_influx.lua"

[InfluxEncoder.config]
suffix = "$instance_id"

[HttpOutput]
message_matcher = "Type == 'heka.statmetric'"
encoder = "InfluxEncoder"
address = "$influx_proto://$influx_addr/db/$influx_db/series"
method = "POST"
username = "$influx_user"
password = "$influx_password"
